#!/bin/bash
docker-compose -f docker-compose-init.yml up -d --build
# wait for init container to stop
docker wait odoo_init
# start instances
docker-compose -f docker-compose.yml up -d --build --remove-orphans